### PR TITLE
[ci skip] Add SaltyEmu as a community example

### PR DESCRIPTION
**Pull request by BlowaXD**
Hi,

I'd like to add [SaltyEmu](https://github.com/BlowaXD/SaltyEmu) (an MMORPG server Emulator) as another community example which is not a Discord Bot 

Regards,
Blowa.

### CODE REVIEW

**Comment by jacksonrakena** [comment]
Looks good to me, after looking at the repository in question's code.

**Review by Quahu — CHANGES_REQUESTED** [review]
[ci skip] is required for non-code changes.

**Review by BlowaXD — COMMENTED** [review]
Done :)

**Review by Quahu — APPROVED** [review]

**Comment by Quahu** [comment]
Awesome, thanks.

**Pull request merged**
